[core]
# enable debug mode
debug = true
walletname = "main"  #测试服:test,正式服:main

# log相关配置
[log]
log_env = "test"     # dev 不输出log文件，在控制台打印日志，test，pro 会在当前目录创建log并输出log
log_level = "debug" # 日志级别
log_path = "./log/minigame/1000"  # 日志输出路径
log_days = 3       # 日志保留的天数

# 游戏相关gate配置
[gate]
max_conn_num = 20000
pending_write_num = 2000
max_msg_len = 30720
ws_addr = ":3658"
http_timeout = 10 # 单位s
cert_file = ""
key_file = ""
tcp_addr = ""
len_msg_len = 2
little_endian = false
heartbeat = 30 # 单位s

# Redis server config
[redis]
host = "redis"
port = 6379
dialread_timeout = 5
dialwrite_timeout = 5
dialconnect_timeout = 5
password = "L9CTENWNrrjRL9CTENWNrrjR"


# Mysql server config
[database]
host = "mysql"
port = 3306
dbname = "game_vietnam"
password = "L9CTENWNrrjRL9CTENWNrrjR"
username = "root"
args = "charset=utf8"
buf_size = 10
max_idle_conns = 20
max_open_conns = 15
show_sql = true

#webServer
[webServer]
addr=":6034"

[mg]
game_id=100
server_id = 1000

[mg_bbs]
betTime = 30
endTime = 5
caiJin = 10000000
triggerLottery= 1000000
chipList = "1000 2000 3000 4000 5000"

[open]
#空格分开
modules="gate web minigame"
