server{
    listen 80;

    access_log /var/log/nginx/vietnam.com_access.log;
    error_log /var/log/nginx/vietnam.com_error.log;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
            root   /www;     #网站根目录
            index  index.html index.php;    #默认首页，改为index.php以便支持php网页
        }
}


