
FROM ubuntu AS runner

# 更新软件包列表并安装tzdata
RUN apt-get update && apt-get install -y tzdata && apt-get -qq install -y --no-install-recommends ca-certificates curl

# 设置时区为东八区
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata

# 清理不需要的软件包和缓存
RUN apt-get clean && rm -rf /var/lib/apt/lists/*